### ISSUE TITLE
Empty <td data-label="Test"></td> breaks table layout

### ISSUE THREAD

**Issue by anselal** [Chalarangelo/mini.css#101]
I noticed that when the `<td>` is empty and we have specified a data-label then the table layout breaks at that point. In the attached screenshot the "td 3' is empty.
![2017-10-15_14h21_24](https://user-images.githubusercontent.com/8732668/31584261-23f3425c-b1b4-11e7-8198-ae1e6cd59976.png)

**Comment by anselal** [comment]
A hack to fix this is to add a `&nbsp` if there is no value for that field but I was wondering if this could be fixed within the framework

**Comment by Chalarangelo** [comment]
I was literally writing about `&nbsp;` a second ago. This is a problem I have never encountered, but then again I have not had empty `<td>` elements. I will try to fix this asap and release a hotfix in the next couple of days. Sorry for the inconvenience!

I am also tagging this as `help wanted` and `good first issue` for new contributors to work on, if they so desire, as I am a little bit swamped with **Gluon** and other projects. However, this is a high priority bug that will be fixed! You have my word.

**Comment by anselal** [comment]
Maybe setting a minimum default height for the rows will fix the issue.

**Comment by Chalarangelo** [comment]
@anselal that sounds like a plausible solution. You could give it a try and, if it works, you could open a PR?

**Comment by anselal** [comment]
I will give it a quick try but I don't promise anything since I am not familiar with scss yet

**Comment by Chalarangelo** [comment]
@anselal try it in CSS in a Codepen or something. If it works, I will patch up the SCSS myself and release it immediately. Sorry for not looking into it right away, I have a college assignment that is due in two days and time is extremely limited till tomorrow.

**Comment by Chalarangelo** [comment]
Resolved in 7fb18b0 and released in [`v2.3.5`](https://github.com/Chalarangelo/mini.css/releases/tag/v2.3.5). Thanks for reporting and helping resolve this!

**Comment by anselal** [comment]
Hi there,

I was reading about table formatting with css and stepped into a property which maybe is a better solution than the one o proposed earlier. Are you aware of the css property `empty-cells: inherit;` ?
May this one is better than adding a default minimum width ?

**Comment by Chalarangelo** [comment]
No, I have never seen this before. In fact, [Can I use...](https://caniuse.com/#search=empty-cells) does not even find it if I search for it. W3Schools mentions it is CSS2 so it *should* be supported well enough. I will look into it and see if it's any better than the existing solution. Thanks for the heads up!
