### ISSUE TITLE
onclick handlers on dynamically created radio buttons wont work

### ISSUE THREAD

**Issue by aguaviva** [Chalarangelo/mini.css#106]
```
$("#answers").html("<input type='radio' name='group' tabindex='0' onclick='alert(\"hello\")'><label>hello</label>")
```

this is caused probably by the radio hack, I workaround it by putting the onclick in the label

**Comment by Chalarangelo** [comment]
This is in fact part of the tradeoff for using the radio hack. The `label` of the radio is the intended element to be clicked and to have the `onclick` handlers. I do not think that there's anything to be done about this, except use Javascript to fix it somehow.
