### ISSUE TITLE
Drawer is not working

### ISSUE THREAD

**Issue by TotallyInformation** [Chalarangelo/mini.css#112]
* Framework Version:
Latest (https://gitcdn.link/repo/Chalarangelo/mini.css/master/dist/mini-default.min.css)
* Flavor used:
Default
* Operating System/Browser:
Windows 10, Chrome (latest)
* Code to reproduce:
Your example from the quick reference page:
https://codepen.io/chalarangelo/pen/JNvPrB
* Screenshots:
* Bug description:
Hamburger menu does not appear. Some kind of boxed horizontal grid is drawn under the header.
* Additional information (Optional):
None of the examples given in the documentation work.

**Comment by Chalarangelo** [comment]
It works exactly as expected. The `.drawer` component is a responsive component, meaning that if the viewpor is above `768px`, its contents will display as a normal piece of navigation, thus the boxed horizontal grid under the header. If you resize the viewpor on the Codepen to below `768px`, you will see its toggle. You can use `.persistent` to make a drawer always be a drawer, no matter the viewport size.
