### ISSUE TITLE
Heading links are broken

### ISSUE THREAD

**Issue by mariastervic** [Chalarangelo/mini.css#114]
* Framework Version: v3.0.0-alpha.1
* Flavor used: default
* Operating System/Browser: Firefox (latest) on Windows 8
* Code to reproduce: [fiddle](https://jsfiddle.net/7j27y8f2/1/)
* Screenshots: n/a
* Bug description: I've noticed that heading elements do not display properly if their whole text is a link. Wrapping the heading element in a link works as expected, but not the reverse.
* Additional information (Optional): n/a

[Note]: # (Please describe what the bug is, what component/module causes it and how it differs from expected/intended behavior)
[Note]: # (Include screenshots of the reported bug whenever possible to best clarify)
[Note]: # (Always try to include code to reproduce the problem, as well as system specifications to make tracking easier)
[Note]: # (Codepen links, additional information, suggestions, articles etc. are greatly appreciated)
[Note]: # (If you want to suggest a feature or your issue doesn't classify as a bug report, please do not use this template)

**Comment by Chalarangelo** [comment]
Thanks for reporting this! I noticed it, too, a couple of days ago. This is already on my list, so expect it to be fixed before the release of the first **Gluon** alpha.

**Comment by Chalarangelo** [comment]
This has been resolved in the latest commit of the **Gluon** branch. It should be usable as soon as the alpha releases. Thanks for finding this bug!
