### ISSUE TITLE
Problem when php code embedded

### ISSUE THREAD

**Issue by tk5ep** [Chalarangelo/mini.css#117]
* Framework Version: 2.3
* Flavor used: none
* Operating System/Browser: W10 64 bits
* Bug description: when embedding php code in the navbar, the menu does not collapse when screen size gets lower.

`<body>
<header class="sticky">
<div class="col-sm col-md-10 col-md-offset-1">
 	<a href="index.php" class="logo"><img src="./icons/bee-logo.png" height="40" width="40"></a>
	<label class="drawer-toggle button" for="navigation-toggle"></label>
    <a href="index.php" role="button">Home</a>

	 <?php
	// if admin access to admin menu
	if ( isset($_SESSION['admin']) && $_SESSION['admin']=='1' )
	{
		echo"<a href='apaguard_adminusers.php' role='button'>Gestion utilisateurs</a>";
		echo"<a href='apaguard_adminapaguard.php' role='button'>Gestion Apaguards</a>";
		echo"<a href='apaguard_adminruchers.php' role='button'>Gestion ruchers</a>";
		echo"<a href='apaguard_adminruches.php' role='button'>Gestion ruches</a>";
	}

	// if logged, access to user menu	
	elseif ( isset($_SESSION['proprietaire_id']) )
			{
				echo"<a href='apaguard_edituser.php' role='button'>Mon compte</a>";
				echo"<a href='change_password.php' role='button'>Password</a>";
				echo"<a href='apaguard_editruche.php' role='button'>Ruches</a>";
				echo"<a href='apaguard_editrucher.php' role='button'>Ruchers</a>";
				echo"<a href='apaguard_editapaguard.php' role='button'>Apaguards</a>";
				echo"<a href='apaguard_datas.php' role='button'>Données</a>";
			}
		else
	{
	echo"
	<a href='apaguard_graph.php' role='button'>Demo</a>
	<a href='apaguard_tech_infos.php' role='button'>Techniques</a>
	
	";
	}		
	// dynamic login menu
			if ( !isset($_SESSION['proprietaire_id']) )
				{
					echo"<a href='login.php' role='button'>Login</a>";
				}
			else 
			{
				echo "<a href='logout.php' role='button'>Logout</a>";
			}
		// if not logged, display visitor menu
	?>
</div>
</header>
<input type="checkbox" id="navigation-toggle">
<nav class="drawer hidden-md hidden-lg">
<label class="close" for="navigation-toggle"></label>
<a href="index.php"><h4 style="margin-left: 0;">Home</h4></a>
<a href="paguard_graph.php"><h4 style="margin-left: 0;">Demo</h4></a>
<a href="apaguard_tech_infos.php"><h4 style="margin-left: 0;">Techniques</h4></a>
<a href="login.php"><h4 style="margin-left: 0;">Login</h4></a>
</nav`

https://ibb.co/d3HRoR

**Comment by Chalarangelo** [comment]
Hi there! From the embedded image, I see that the top navigation bar (`header`) behaves exactly as expected, showing a scrollbar for anything off-screen. What seems to be the problem?

I have thoroughly tested the framework in combination with PHP and I can tell you it's almost certainly not a problem with the PHP being present, but rather a problem with the markup generated.

**Comment by tk5ep** [comment]
Hi Angelo,
Thanks for information.
Than it is probably a problem in my markup.

I saw in some examples, that when out of screen, there is no scrollbar but only the drawer...  I thought that was the normal behaviour.
Will try to find out what's wrong, but for a newcomer, it's a bit hard... 

`http://www.egloff.eu/apaguard_mini/`

Thanks,

**Comment by Chalarangelo** [comment]
The header's contents do not magically move into the drawer, but this can be very easily solved as follows:
```html
<header>
  <a href="#1" class="hidden-sm">Link 1</a>
  <a href="#2" class="hidden-sm">Link 2</a>
<label for="drawer-check" class="drawer-toggle"></label>
</header>

<input type="checkbox" id="drawer-check" />
<div class="drawer">
  <a href="#1" class="hidden-md hidden-lg">Link 1</a>
  <a href="#2" class="hidden-md hidden-lg">Link 2</a>
</div>
```

In the above example, the links in the `header` are shown except if the screen size is small and the links inside the drawer will only show if the screen size is small. Your drawer can then have any other content you like. Hope this helps!

**Comment by tk5ep** [comment]
That did it !

Now it reacts as expected !
I did not use a div in the drawer, but a nav with the hidden tag, and it works just fine ! 

Sorry for the troubles and thanks for this really nice framework ! Keep up the good work.

Now i have to solve the form responsivity...
BTW, is there forum, blog where i can ask help ?
Patrick,

**Comment by Chalarangelo** [comment]
There is a [gitter channel](https://gitter.im/minicss/Lobby), but it's pretty empty right now. Hopefully, it will end up being alive enough for people to get help. I recommend asking questions there as it's a better fit than opening issues most of the time and there might be more people willing to help out as time goes by.

You can also try StackOverflow (there is no tag for the framework yet, hopefully there will be one sometime), I am also very active there so I will probably end up answering any questions you might have same as I do here.

**Comment by tk5ep** [comment]
Great,
I also asked on Stackoverflow. You probably overlooked my post.
Indeed, there is no tag for mini.css.
No clue what gitter is, will have a look and probably post there.. ;-)

Thanks a million,

**Comment by Chalarangelo** [comment]
Well, I just found the question and responded there with the solution. I also added the tag for **mini.css**, although I wouldn't expect it to be accepted as there are not many other questions about it.
