### ISSUE TITLE
[docs] Mismatched opening/closing tags in example

### ISSUE THREAD

**Issue by tinybarks** [Chalarangelo/mini.css#119]
In `docs/table.html` and `docs/quick_reference.html`, there's the "Star Wars Character Alignment Table", an example for matrix tables. Unfortunately, the top row reads:

```html
      <th>Lawful</td>
      <th>Neutral</td>
      <th>Chaotic</td>
```

While this probably renders fine in any browser since they just figure it's a mistake, this should of course be:

```html
      <th>Lawful</th>
      <th>Neutral</th>
      <th>Chaotic</th>
```

The CodePen also is affected.

I would've submitted a PR, but there don't seem to be any sources for the docs.

**Comment by Chalarangelo** [comment]
Hello, thanks for reporting this! The source code for the docs is in the `docs` folder, as the website is hosted via Github pages. If you have the time, submit a PR and I will merge that asap and I will also fix the Codepen.
