### ISSUE TITLE
The Scroll on horizontal Table 

### ISSUE THREAD

**Issue by githubjeka** [Chalarangelo/mini.css#123]
* Code to reproduce:
https://jsfiddle.net/d4xrbm3r/

* Bug description:
On *lg and *md grid the table with class `.horizontal` you can see:

In **Google Chrome**:  the unnecessary scroll. When `td` uses style `text-align: right` this prevents comfortable viewing of information
![image](https://user-images.githubusercontent.com/874234/36013591-2359caa0-0d76-11e8-8ef0-ab12dbc8782e.png)

**Comment by Chalarangelo** [comment]
This is mainly an issue with how Chrome renders tables (horizontal tables are quite hacky anyways). I am pretty sure that I do not know how to deal with this, so if anyone is able to help out, please do.

The latest `Gluon` alpha does not seem to have the same problem, while the code is almost the same. This is particularly strange...
