### ISSUE TITLE
Feature suggestion: Footer class - stick to bottom

### ISSUE THREAD

**Issue by datiswous** [Chalarangelo/mini.css#124]
It would be nice to have a footer class to stick it to the bottom when page content is less on bigger screens.

**Comment by Chalarangelo** [comment]
There is a `.sticky` class for the `footer` element. However, this has been brought up before (ie `footer` does not stick to bottom when there is not enough content). This can be overriden by adding some custom CSS as it is not a feature that the framework supports out of the box. 

There are plenty of tutorials and/or questions around the web. I think that [this answer](https://stackoverflow.com/a/18066619/1650200) will lead you in the right direction.

**Comment by aguaviva** [comment]
I'd be much appreciated if this was in the documentation, "footer does not stick to bottom when there is not enough content"
