### ISSUE TITLE
toast not changing color on error warning class

### ISSUE THREAD

**Issue by wighawag** [Chalarangelo/mini.css#125]
* Framework Version: 2.3.7
* Flavor used: dark
* Operating System/Browser: windows/chrome
* Code to reproduce:  ```<span class="toast small error">This is a  toast message! <span class="close">```
* Screenshots:
* Bug description: I expected the toast to take a red background color
* Additional information (Optional):

**Comment by Chalarangelo** [comment]
The `toast` component does not feature an `error` class, however you can manually override its background, by adding something like:
```css
.toast.error{
  background: red;
}
```
