### ISSUE TITLE
GitCDN Repository is Forbidden

### ISSUE THREAD

**Issue by mookman288** [Chalarangelo/mini.css#126]
* Framework Version: newest
* Flavor used: default
* Operating System/Browser: null
* Code to reproduce: visit https://gitcdn.link/repo/Chalarangelo/mini.css/master/dist/mini-default.min.css
* Screenshots: none
* Bug description: The repository has been blacklisted on gitcdn, and as a result returns a forbidden error when trying to pull from CDN. 
* Additional information (Optional):

Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist.

**Comment by Chalarangelo** [comment]
Thanks for the heads up!

It seems like the compressed file is blacklisted, but the uncompressed one (without `.min`) is not. I already opened an [issue](https://github.com/schme16/gitcdn.xyz/issues/36) about this, feel free to add any relevant information in a comment under it.

**Comment by Chalarangelo** [comment]
This seems to have been resolved on their end, so I am closing this issue.
