### ISSUE TITLE
Tooltips placing and visibility

### ISSUE THREAD

**Issue by Titum** [Chalarangelo/mini.css#128]
* Framework Version: 2.3.7
* Flavor used: default

Thank you for the very good work on this project!

It may be usefull, at least for me :) to have classes as simple as .bottom to position the tooltips to the rigth or to the left of the HTML element containing the aria-label attribut.

Also, the tooltip is hidden in sections of cards at the edges of the card:
`<div class="card">
	<div class="section">
		<span class="tooltip" aria-label="Text of the tooltip">Test</span>
	</div>
</div>`

Thank you!

**Comment by Chalarangelo** [comment]
I am marking this as `on hold` not due to this being a bad feature, but mainly because I am not planning to add it to framework. I will, however, provide a demo with the additional classes requested and link to it from the documentation for people who might want to use these classes.
