### ISSUE TITLE
Some improvement for your website and github

### ISSUE THREAD

**Issue by Kidounet** [Chalarangelo/mini.css#131]
I love this css framework ( used for my website http://camarilla-fr.com ), but since V3, it's less easy to get docs :

- Can you redirect all 404 error page from https://minicss.org to the homepage ? all page referenced by google  is 404 and very bad for this framework.

- can you add all changes and the last version in CHANGELOG.md (like github release page https://github.com/Chalarangelo/mini.css/releases ). all github code is V3 but changelog is v2.3.7 -_-

- can you repport all breaks elements in V3.0.0 (non alpha) release info in github and changelog ?

- and last but not important, add a migration (v2 to v3) section in doc will be appreciate ^^

very good job for this new major version. i'll go to migrate my website as soon as possible.
Kidou

**Comment by Chalarangelo** [comment]
Thanks for bringing this to my attention. V3 has had a bit of a rough launch so far, but most of these issues will be fixed. More specifically:

- 404 pages should not be redirected, Google has forgotten to crawl the website, I'm doing my best to bring this to their attention. All of the docs are now in one place: https://minicss.org/docs - Just bookmark that and you shall be fine.
- CHANGELOG.md has been forgotten - I'll definitely update that as soon as I can.
- Breaking changes will be included in the CHANGELOG.md file. As a reference, `table` has had some major changes, `tab` is not present any more, everything else is pretty much the same but might behave a tiny bit differently. Also, `checkbox` and `radio` have had some changes made to them, I will elaborate in the log. 
- A migration page should be added soon to address some of these issues, too.
