### ISSUE TITLE
Drawer from  the left?

### ISSUE THREAD

**Issue by slacktracer** [Chalarangelo/mini.css#134]
I'm looking for an example of the drawer opening from the left. Is it even possible?

Did not find anything in the docs so far...

Anyway, thank you! Mini.css looks really great. =)

**Comment by Chalarangelo** [comment]
Sure, you can change the [`$_drawer_right`](https://github.com/Chalarangelo/mini.css/blob/master/src/mini/_navigation.scss#L36) variable to move the menu to the left.
