### ISSUE TITLE
iOS Menu Drawer not showing in sticky header

### ISSUE THREAD

**Issue by ciknowles** [Chalarangelo/mini.css#136]
* Framework Version:3.0.0
* Flavor used:nord
* Operating System/Browser:Safari
* Code to reproduce:
<header class="sticky row">
				<a href="#" class="logo col-sm-1 col-md" >E</a>
				<label style="line-height:3" class="col-sm col-md">Title</label>
					<label for="main-drawer-control" class="drawer-toggle persistent"></label>
					<input id="main-drawer-control" class="drawer persistent" type="checkbox">
					<div>
						<label for="main-drawer-control" class="drawer-close"></label>
				<div class="col-sm-12" ><button style="text-align:left;width:100%" href="_blank" value="help">Help</button></div>
<div class="col-sm-12" ><button style="text-align:left;width:100%" href="_blank" value="help">Help</button></div>
<div class="col-sm-12" ><button style="text-align:left;width:100%" href="_blank" value="help">Help</button></div>
					</div>
				
			</header>
* Bug description:
This bug ONLY happens in safari. So affects iphone and ipad and safari on Mac.
When a Header (sticky) contains a Menu Drawer the menu fails to display correctly. The parts of the menu outside the header are not displayed.

This be fixed by removing  position:-webkit-sticky; for the css for header.sticky

header.sticky {
 position:-webkit-sticky;
 position:sticky;
 z-index:1101;
 top:0
}

**Comment by ciknowles** [comment]
The other way to fix it is to reverse the order of the position styles

Before:
header.sticky {
 position:-webkit-sticky;
 position:sticky;
 z-index:1101;
 top:0
}

AFter:
header.sticky {
 position:sticky;
 position:-webkit-sticky;
z-index:1101;
 top:0
}

**Comment by Chalarangelo** [comment]
I have not managed to reproduce this bug so far. More information would be appreciated.

**Comment by ciknowles** [comment]
Hi, 

I resolved this issue. I had assumed that the menu html would be in the header element. Looking at your example the label is but the rest is in a row. 

Well done with minicss - nice features and not too many!
