### ISSUE TITLE
cloudflare link doesn't really work

### ISSUE THREAD

**Issue by diomed** [Chalarangelo/mini.css#137]
title says it all

`https://cdnjs.cloudflare.com/ajax/libs/mini.css/v3.0.0/mini-default.min.css`
is 404

**Comment by Kidounet** [comment]
hi,
you can use : https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.0/mini-default.min.css

**Comment by Chalarangelo** [comment]
That's an easy fix, I'll update the docs as soon as I get a chance! Thanks for bringing this to my attention!

**Comment by Chalarangelo** [comment]
Fixed, should be ok now.
