### ISSUE TITLE
Applying styles based on WAI-ARIA role is not helpful

### ISSUE THREAD

**Issue by nborko** [Chalarangelo/mini.css#142]
* Framework Version: 3.0.0
* Flavor used: default

This is not a bug report, but rather general feedback.

The framework is great, in general I like the issues it addresses. On the issue of the styling of content based on WAI-ARIA role, I feel that forcing a visual style on an element that is flagged to convey information for semantic purposes to assistive devices (screen readers et. al.) is unhelpful, to the point that I've had to manually edit and remove all selectors with [role="button"] from the stylesheet.

There are many reasons to assign ARIA roles to elements, and most of them have nothing to do with visual style. WAI-ARIA roles exist as hints to user agents to elicit an expected behavior from the user agent, in most cases an assistive device. Using the role attribute to change the visual style works against the effort to make visually complex layouts accessible.

Thanks for your time.

**Comment by Chalarangelo** [comment]
Buttons should look like buttons and display as buttons to screen readers. Tightly coupling visual appearance and assistive technologies is a deliberate choice.
