### ISSUE TITLE
Wrong behavior when using <label> instead of <div> on angular

### ISSUE THREAD

**Issue by kennykarnama** [Chalarangelo/mini.css#144]
* Framework Version:
v3.0.0
* Flavor used:
Angular app
* Operating System/Browser:
Ubuntu 18.04/Mozilla Firefox
* Code to reproduce:
`<label for="modal-control" class="modal-close" ></label>`
* Bug description:
When using angular, the label element gives wrong behavior. I suggest to change it to be  
`<div for="modal-control" class="modal-close"></div>`

**Comment by Chalarangelo** [comment]
Using `<div>` is semantically incorrect. As far as I'm concerned, this is more of an issue with how angular deals with things rather than an issue with the framework.
