### ISSUE TITLE
Support for more [colour] icons

### ISSUE THREAD

**Issue by anselal** [Chalarangelo/mini.css#146]
Hi there,

is it possible to add more feather icons ?

I would like some icons like delete and add which are helpful when creating forms etc.

Also is it possible to add colour to the icons ?

**Comment by dtmpsc** [comment]
They're all in the CSS file, down near the bottom. For instance, I added the heart icon.

span.icon-heart {
  background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-heart'%3e%3cpath d='M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z'%3e%3c/path%3e%3c/svg%3e");
}

Just download the svg of the icon you wish to add, then convert it here:

https://codepen.io/elliz/full/ygvgay

**Comment by anselal** [comment]
Nice !!! Thnx !!!

**Comment by anselal** [comment]
@Chalarangelo Is it ok if I create a PR and add more feather icons ?

**Comment by Chalarangelo** [comment]
@anselal Not really. The icon set and amount of items is pretty much locked, just to keep the filesize small. I was planning to make an icon tool that will add icons on-demand, but work got in the way and I have very limited time to do so. Maybe you could help with that, so that people can add icons to their flavors as they please?

**Comment by anselal** [comment]
My time is limited too due to work load but If you could give me some instructions on how you would like this tool to be I could try to implement it.
What exactly do yo have in mind ?

**Comment by Chalarangelo** [comment]
I was thinking a tool that uses the Feather package to get a list of images, then lets the users choose which ones they want to add to their flavor and they are added via SCSS to the flavor file or single, small CSS files with the icons as classes.

**Comment by anselal** [comment]
I see. Perhaps we can pre-create the SCSS for the feather-icons so it would be easier to add them to the flavor. Maybe we can create a feathericons-css inside https://github.com/feathericons

You think we can contact them and ask to give us write access to a repo inside their organization ?

**Comment by Chalarangelo** [comment]
I am going to close due to inactivity. Feel free to comment below to reopen if you want to help with this.
