### ISSUE TITLE
Support for night mode out of box

### ISSUE THREAD

**Issue by AucT** [Chalarangelo/mini.css#148]
I know that everyone can do it by herself, but I'm a programmer who doesn't wanna touch css much.

I think framework can gain some more popularity (and help me :P) if it has night mode css colors. 

I'm thinking of when body tag has class "night" it will convert everything into night mode.

**Comment by Chalarangelo** [comment]
We already have the dark flavor for this, so I am not going to add extra bloat to any existing flavor, **but** a plugin for this would be welcome.
