### ISSUE TITLE
Table: flex and word-wrap problem

### ISSUE THREAD

**Issue by sommer-gei** [Chalarangelo/mini.css#151]
* Framework Version: v3.0.1
* Flavor used: Default
* Operating System/Browser: FF 60.3.0esr (64-Bit)
* Code to reproduce: https://jsfiddle.net/vLjx4ubm/
* Bug description:

I have to show long strings in a table.  − Like you can see in the JSFiddle with mini.css (out-of-the-box) it’s not possible to show the whole (wrapped) strings. Also the text is going out of the column + table boundaries.
Then I fiddled a lot around and found (thought so) a simple solution. − Adding: `overflow-wrap: break-word;` to the table. But that seems not fully work.

**Q1:** How can I get a correct shown (flex/mini.css) table (incl. headings) with fully shown (and wrapped) long strings?
(**Q2:** Is it possible to add a second/alternate color to `<code>` in a striped table, for the alt. columns, please!?)

Thanks a lot for your reply in advance! − Also thanks for "mini.css"! :-)

**Comment by Chalarangelo** [comment]
Tables are a tricky beast in CSS. I'll take a look as soon as I have some free time, might come up with a solution.

**Comment by Chalarangelo** [comment]
First off, the way that you use the table is entirely semantically incorrect. `overflow-wrap: break-word` will actually help with most of the other normal use-cases. I'm closing and I will push a fix shortly.
