### ISSUE TITLE
Need a css and min.css download link so we do not have to use sass.  

### ISSUE THREAD

**Issue by slloyd88** [Chalarangelo/mini.css#153]
* Framework Version:
* Flavor used:
* Operating System/Browser:
* Code to reproduce:
* Screenshots:
* Bug description:
* Additional information (Optional):

[Note]: # (Please describe what the bug is, what component/module causes it and how it differs from expected/intended behavior)
[Note]: # (Include screenshots of the reported bug whenever possible to best clarify)
[Note]: # (Always try to include code to reproduce the problem, as well as system specifications to make tracking easier)
[Note]: # (Codepen links, additional information, suggestions, articles etc. are greatly appreciated)
[Note]: # (If you want to suggest a feature or your issue doesn't classify as a bug report, please do not use this template)

**Comment by slloyd88** [comment]
Need a css and min.css download link so we do not have to use sass.

**Comment by lemmingz** [comment]
From the "getting started" section:
> Alternatively, you can use either **rawgit** or **cdnjs** to import **mini.css** into your HTML page's `<head>` tag:
> 
> `<link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css">`
> `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">`
