### ISSUE TITLE
Please provide examples of a responsive header

### ISSUE THREAD

**Issue by greencopper** [Chalarangelo/mini.css#155]
In the documentation you write:

> The header element can be a row in a grid system, allowing you to create responsive headers.

And also:

> It is recommended that you combine the navigation bar element with the grid system to create responsive navigation menus for your web apps.

Could you please provide at least one example of each on how to do this?

Best regards.

**Comment by Chalarangelo** [comment]
Fair enough, I will add an example as soon as I have some time to spare.

**Comment by Chalarangelo** [comment]
Actually, this is really straightforward from the existing documentation, you should use `header.row` and you can add columns inside it if you wish. I'm closing this, as it doesn't seem to need a lot of clarification.
