### ISSUE TITLE
Error in doc sample for Forms and Input - Best Practice

### ISSUE THREAD

**Issue by HamptonNorth** [Chalarangelo/mini.css#156]
Incorrect code sample - several divs closed before class declaration

```
<div> class="row">
      <div> class="col-sm-12 col-md-6">



<div> class="col-sm-12 col-md-6">

```

![mini-css-docs-fault](https://user-images.githubusercontent.com/1650551/60757802-2061b400-a007-11e9-973c-afd4b1f36649.png)

**Comment by Chalarangelo** [comment]
Rebuilding docs fixed this. Thanks for reporting.
