### ISSUE TITLE
Header logo not vertically centered when .row is applied to the header

### ISSUE THREAD

**Issue by DeltaRazero** [Chalarangelo/mini.css#158]
* Framework Version: 3.0.1
* Flavor used: Default
* Operating System/Browser: Win10 Chrome (latest)
* Screenshots:

![image](https://user-images.githubusercontent.com/26445643/61038571-89fa0d80-a3cd-11e9-9706-266c575b2943.png)
```
<header>
    <a href="#" class="logo">Logo</a>
    <a href="#" class="button">Home</a>
    <button class="">Download</button>
</header>
```
---

![image](https://user-images.githubusercontent.com/26445643/61038594-93837580-a3cd-11e9-9ece-6583ae253488.png)
```
<header class="row">
    <a href="#" class="logo">Logo</a>
    <a href="#" class="button">Home</a>
    <button class="">Download</button>
</header>
```

* Bug description:
The element assigned with .logo is no longer vertically centered when .row is applied to the header tag.

**Comment by Chalarangelo** [comment]
I will look into it soon. Seems like an easy fix.
