### ISSUE TITLE
The class="switch" does not work as expected.

### ISSUE THREAD

**Issue by g-vvv** [Chalarangelo/mini.css#160]
The class="switch" does not work as expected.

Framework and Flavor used:
https://gitcdn.link/repo/Chalarangelo/mini.css/master/dist/mini-default.min.css

Codepen example:
https://codepen.io/chalarangelo/pen/rwxBPv

**Comment by sigmasoldi3r** [comment]
What it should do?

**Comment by g-vvv** [comment]
It does not matter anymore ;)
You can close this issue.



На ср, 22.01.2020 г. в 9:30 Pablo Blanco Celdrán <notifications@github.com>
написа:
