### ISSUE TITLE
Link color in dark mode is very dark

### ISSUE THREAD

**Issue by acnance87** [Chalarangelo/mini.css#164]
* Framework Version: 3.0.1
* Flavor used: Dark
* Operating System/Browser: PC/Firefox
* Code to reproduce: create any link in the markup
* Screenshots: n/a
* Bug description: suggestion/improvement
* Additional information (Optional):

[Note]: # Dark flavor might benefit from a lighter link color

**Comment by niftyrinki** [comment]
Working on it
