### ISSUE TITLE
Question about android support? [v2]

### ISSUE THREAD

**Issue by ozgurrgul** [Chalarangelo/mini.css#39]
Right now I'm using [w3css](http://www.w3schools.com/w3css/) for a project, but I saw mini.css and decided to migrate it. The project will be used mostly in Android 4+ devices. 

So, I wonder which features are supported by mini.css in Android devices? I really want to use mini.css.

Thank you!

**Comment by Chalarangelo** [comment]
It all comes down to browsers. Most Android users view pages in either the default Android browser, Chrome, Firefox or some variation of the above (I think the browser component of Android's libraries is based on the default Android browser as well).

Most of the framework is compatble with all of the latest versions and a lot of version before them. Android 4+ should support everything, but there might be a couple of oddities like the animation blurring (#35) for animated alerts. Older versions will probably support everything except maybe a few minor things like a feature query somewhere (which is not a huge deal) and maybe the `object-fit` of `.card.section.media` class. These can be dealt with using some extra CSS, which is not a huge deal>

However, if the browsers you are targeting are really old and not support Flexbox (either latest specor the older spec), you might want to try another UI toolkit, as a lot of the modules are based on Flexbox (grid, card, tab, parts of table and input_control).

**Comment by ozgurrgul** [comment]
Thanks for your fast reply Angelos. Most of the Android browsers based on WebView so there shouldn't be any problem except UC, Opera etc, because they are using custom renderers. But I saw you said mini.css supporting uc, opera etc. So there is no problem in my case.

Thanks again.
