### ISSUE TITLE
CSS tooltip

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#41]
This is a relatively [simple enhancement](http://www.w3schools.com/css/tryit.asp?filename=trycss_tooltip). A simple .tooltip class or make use of the role="tooltip".

You can also possibly customize the conditions for tooltip popup via classes, ie. classes for activating the tooltip on :hover (probably the default) and :active for click events. Something like:

    .tooltip { cursor: pointer; }
    .tooltip>[role="tooltip"] { visibility: hidden; }
    .tooltip.onhover:hover>[role~="tooltip"] { visibility: visible; }
    .tooltip.onclick:active>[role~="tooltip"] { visibility: visible; }

So some markup could use it as follows:

    <div class="tooltip onhover">?<div role="tooltip">This is the tooltip text</div></div>

See [working codepen](http://codepen.io/anon/pen/woOdVz).

**Comment by Chalarangelo** [comment]
A [sample codepen](http://codepen.io/chalarangelo/pen/apNrgL) for the tooltip component is available here. Implementation is still in the very early stages, but I'm confident this component will make it into **v2.1.0**, which is due for release sometime next month.

If the component is lightweight enough, which is highly probable, it will be part of the framework and I will in fact merge it into the *contextual* module, where it belongs. Mixins might also be available, but the *mini-default* flavor will most likely only include a default color variant (dark background, light colored text).

**Comment by Chalarangelo** [comment]
**Update**: The tooltip component is in active development right now and most of the details have already been ironed out. 

If it makes it into the *contextual* module, you should expect two tooltip styles, based on an exclusive flag: `top` or `bottom` styles. More tooltip styles might be coming in the future.

**Comment by Chalarangelo** [comment]
**Update**: The flag mentioned in my previous comment is not going to be mutually exclusive. The default style of the tooltips will be `top` and a `.bottom` class will be available to show tooltips the other way round. 

Standard mixins will also be available, named something like `make-tooltip-alt-color` and `make-tooltip-alt-style`, similar to most of the other available mixins. More info will be available after the component is complete.

**Comment by Chalarangelo** [comment]
**Update**: The tooltip component is now complete. There might be a few tiny errors in terms of certain calculations but I'll retest everything and polish the component before release a bit more.
