### ISSUE TITLE
Stick footer to the bottom of its context

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#42]
How to stick a footer to the bottom of a page or some enclosing box is a pretty common problem. It'd be nice if you could just stick a class to your `<footer>` element and have it just work.

For instance, I just forked the footer codepen and [added this class](https://codepen.io/anon/pen/aBMwZX) as an example of the desired behaviour. It's probably not ideal though.

**Comment by Chalarangelo** [comment]
After some tinkering, I came up with the code shown in [this codepen](https://codepen.io/chalarangelo/pen/QdjLaG) to solve the problem. It seems to work fine, without altering any of the original styling of the  `<footer>` element, making this an ideal implementation of the functionality that was suggested. I will be implementing this shortly in the `2.1.0` branch.

**Comment by Chalarangelo** [comment]
The implementation leaves something to be desired, as I need to make the parent element (`<body>`) use `position: relative;` and also the `<footer>` does not really respect the boundaries set by other elements. Further investigation is in fact required.

**This feature might be introduced in v2.1.0 or dropped entirely if no usable solution is found.**

**Comment by Chalarangelo** [comment]
After a little bit of tinkering, I decided to go with a *sticky* footer, utilizing the `position: sticky`, like I did with `<header>` in #26. This is not the best possible solution, but it provides some functionality that is reasonably modern and can easily be enhanced with some Javascript code. Building updated version...
