### ISSUE TITLE
Cards on module page vertically misaligned during resize

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#44]
The cards for the [module page](https://chalarangelo.github.io/mini.css/modules.html) on wide screens start out vertically aligned along the top, but if you shrink the window horizontally the "Core" card looks like it becomes misaligned at some sizes, but it's really vertically centered, which was just surprising.

I expected them to maintain vertical alignment along the top, but if the intent was vertical centering, then please close this ticket.

**Comment by Chalarangelo** [comment]
The intent was in fact vertical centering. Thus, the issue is considered resolved. Have a nice day!

**Comment by naasking** [comment]
Weird, it's still happening in some cases on your website:

https://chalarangelo.github.io/mini.css/modules.html

It's most noticeable for the Core card if you scale to 1024px horizontally, but it happens to the Input Control card around 1004px too (in Chrome). Perhaps the website is not updated?

**Comment by Chalarangelo** [comment]
@naasking Checking it right now in Firefox for 1004px and 1024px in responsive design mode. Nothing wrong with how it displays. The cards are **vertically centered**, not aligned to their top, so this is the intended behavior.

**Comment by naasking** [comment]
Ah, sorry, I was confused because I thought top-alignment was the goal. But there's still an inconsistency here, because at around 1010px the Tab card is top-aligned not vertically centered, and at around 980px Utility card is top-aligned. I can reproduce the same behaviour in Firefox.
