### ISSUE TITLE
Question about class names

### ISSUE THREAD

**Issue by ozgurrgul** [Chalarangelo/mini.css#45]
For example in Bootstrap or similar frameworks, classes are named like `success`, `danger`, `info`. But you chose to implement class names like this:

```
danger -> secondary
success -> tertiary 
```

Why? It looks meaningless and confusing.

**Comment by Chalarangelo** [comment]
This is a decision to make things easier to remember for me. The default flavor is a guideline, you can customize everything, including the names in your flavor. `mini-classic` will feature different names, similar to the ones in Bootstrap.
