### ISSUE TITLE
Generalize input groups

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#50]
[Picnic CSS](http://picnicss.com/tests) allows "stacks" which can group a set of inputs similar to your button-group, but which isn't limited to buttons. Stacks are only vertical there, but it would be nice to have a set of generalized classes, say hgroup and vgroup, for horizontal and vertical input groups.

Or a separate class for grouping works too, ie. class="input-group vertical" and class="input-group horizontal".

**Comment by Chalarangelo** [comment]
This idea sounds interesting, however it might take up too much code, which will bloat the module. I might try to create something like what you suggest but with a smaller scope. This addition might be a long way down the road, as there are more pressing things to deal with (new flavors and some components that have been discussed more than this one).

**Comment by Chalarangelo** [comment]
Implementation of this feature has begun. In fact, the `input-group` component will be extended significantly with something like a `.responsive` class to allow responsive input groups to be created. The old-school `input-group`s will not be removed, however, as they are essential to the checkbox and radio components.
