### ISSUE TITLE
max-width on large screens

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#58]
I had mentioned this on the reddit thread but forgot to create an issue for it. Text is generally only readable on large screens with a max-width around 1024px. For instance, a simple ".readable" class defining this bound that one can use when appropriate. A more opinionated framework might just set this on content elements directly, like p.

I'm honestly not sure if this is something you want to put into mini.css itself though.

**Comment by Chalarangelo** [comment]
Do you mean like the text elements are too wide and spread too far, so it gets difficult to read? I can alter the layout on large screens to deal with this issue, if that is the case.

**Comment by naasking** [comment]
There might be two separable issues. One is that, for example, Quick Overview, Getting Started and Setup&Usage sections spread across the whole page, but would be [more readable if they were bound to less than 1024px](http://baymard.com/blog/line-length-readability). So a class to declaratively specify that some content should conform to readability standards would be useful.

A perhaps more opinionated extension of this issue is whether *all* content should be boundable to 1024px or less. Consider the difference between the mini.css site and [Picnic CSS's](http://picnicss.com/). Your content spreads across the whole page, where Picnic's content stops spreading around 1000px and is centered. A class to declare this would be handy as it's pretty common, but this is the part that I'm not sure whether you'd want to include.

**Comment by Chalarangelo** [comment]
Ok, so something like this should solve the problem for the documentation pages, right?

[![tester.png](https://s27.postimg.org/mjvzrunk3/tester.png)](https://postimg.org/image/l4uf34mgv/)

What I did was add an offset for of 1 column for larger displays on either side. This does not bind the width to 1024px, but should scale nicely for larger display sizes, so very few people might have a problem.

Binding *all* content to `1024px` or something like that will be probably available later down the line, I am interested in the idea, maybe I can build a special grid class that hooks into a `.row` and actually allows for this behavior, like building a centered content column that has a specific bounded width.

**Comment by naasking** [comment]
That looks better. I suppose one could add any number of offsets like you suggested to achieve the effect I'm talking about, so this trick might a good solution for now as an example in the documentation.

**Comment by Chalarangelo** [comment]
Ok, I will incorporate this in the next version of the documentation as a note or example somewhere. Thank you for pointing it out! 👍
