### ISSUE TITLE
breadcrumb overlap problem on chrome

### ISSUE THREAD

**Issue by davidascher** [Chalarangelo/mini.css#72]
Hi, mini.css looks lovely.

I noticed that the demo for breadcrumbs has a visual bug on Chrome OS X Version 57.0.2987.133 (64-bit) (note the middle breadcrumb "Folder":

<img width="989" alt="screenshot 2017-05-04 09 55 42" src="https://cloud.githubusercontent.com/assets/51278/25715308/f59e9a94-30af-11e7-96ba-d104c35142f5.png">

the problem is not visible if you hover on the middle breadcrumb.

**Comment by Chalarangelo** [comment]
This is a sizing bug by the looks of it, which means that the breadcrumb does not fit its assigned column's area. I will change the layout a bit to make sure that this is not an issue in the future. Thank you for reporting this!

**Comment by Chalarangelo** [comment]
I have resolved this locally, will push tomorrow morning (~12 hours from now) along with the next release, which will change a couple of things in the docs and flavors. Stay tuned for the update! :wink:
