### ISSUE TITLE
input text wont appear on Windows phone 

### ISSUE THREAD

**Issue by glomrun** [Chalarangelo/mini.css#87]
Hi i m using Windows phone 8.1 with Internet Explorer. When using mini.css the user input wont appear even if it is here.
Please could you tell me if there is a fix for this ?
This bug also exists when using the login template on http://minicss.org using Windows Phone 8.1

**Comment by Chalarangelo** [comment]
IE is not officially supported for any of the distributed flavors. There could be a fix or some workaround, which will not be patched into the source code, but that you could apply manually. For a fix, however, I would need more information, such as the browser version and a screenshot of the problem.

I would strongly advice you to not use mini.css with legacy browsers such as IE, as it will most definitely cause some issues and you will have to identify, understand and patch them mostly on your own. Develop on and for supported browsers only.

**Comment by glomrun** [comment]
Hi Angelos Chalaris and thank you for your prompt answer :D !

I temporary solved this issue by commenting the lines 734-735 of the file mini-dark.css
line 734 /*-webkit-flex-basis: 0px;
line 735   flex-basis: 0px; */
At that time i also commented the lines 767 and 768 of mini-dark.css

Thank you for your work.

**Comment by Chalarangelo** [comment]
That sounds like a decent enough fix, good job! Bear in mind that this is a problem with Flexbox, upon which mini.css heavily relies. You might find more bugs like this, especially in the card and grid modules.

I will be closing this issue, based on the fact that your problem is resolved. Have a nice day!
