### ISSUE TITLE
Sticky footer doesn't work

### ISSUE THREAD

**Issue by akak0r** [Chalarangelo/mini.css#88]
Hi,

I can't get a sticky footer to work, even though I checked and position:sticky, as mentioned at http://minicss.org/navigation#footer,  should work on the latest version of Chrome.

Would it be possible to implement something like this: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ ?

Thanks.

**Comment by Chalarangelo** [comment]
Hello, thanks for reporting this! I cannot reproduce the bug in the latest version of Chrome. Could you please be more specific about your problem (OS, browser, exact behavior of the bug, screenshots)?

Implementing this using some flexbox trick is not an option as support for `position: sticky` is pretty good and improving, so sooner or later all browsers will support this feature's implementation as-is.

**Comment by akak0r** [comment]
Hi! I made an example here: https://www.dividend-news.com/sticky.html
I'm using Chrome 59 64-bit on Win 10.

The footer isn't being pushed to the bottom when there is little to no content on the page.

**Comment by Chalarangelo** [comment]
This is not what sticky means. Sticky means that the footer will stick to the bottom of the screen. If you want it to go to the bottom and stay there regardless, just use `position: fixed` along with `width:100%`.

**Comment by akak0r** [comment]
Well, everywhere I read about a sticky footer, what is meant is that the footer sticks to the bottom of the screen. Clearly, this is a problem on a page with little content. So imho a sticky footer is a footer that always sticks to the bottom, regardless of the amount of content.

https://css-tricks.com/couple-takes-sticky-footer/

Your solution/suggestion doesn't work (for me), unfortunately.
