### ISSUE TITLE
Check box inside tabs

### ISSUE THREAD

**Issue by umbundu** [Chalarangelo/mini.css#89]
Greetings,
Thank you for such a great job! I wonder if you have plans to change the way the tabs are coded since having radio buttons or check boxes is something quite common.
Thanks,
Everardo

**Comment by Chalarangelo** [comment]
Hi, I'm not particularly sure about them not working and, unfortunately, I am not able to test this right away (probably tomorrow). I think that you can use checkboxes and radio buttons inside tabs as far as those are inside a tab's panel and not freely floating around the tabs container. However, I'll run some tests soon and let you know. If you try anything like that in the meantime, please inform me of your findings! 

Cheers!

**Comment by Chalarangelo** [comment]
## Update

The described functionality is fully usable, as I expected. [Here](https://codepen.io/anon/pen/LLXpoP)'s a quick demo of checkboxes and radio buttons inside a tabbed layout. 

Closing the issue, as there is nothing else needed to be done. Feel free to comment if you have any further questions on the subject.
