### ISSUE TITLE
Add ssl to minicss.org/

### ISSUE THREAD

**Issue by snewell92** [Chalarangelo/mini.css#91]
Not sure where to file this, but using Let's Encrypt and their bot makes it pretty easy to set up ssl certs and renewal. Although I saw in the site's headers that GitHub.com was the server, so is this a form of GitHub pages?

If the docs site was a github.io site [like this one](https://chalarangelo.github.io/), it would get ssl for free, managed by GitHub, then the docs sites could be its own separate GitHub repo too.

Just a thought - feel free to close.

**Comment by Chalarangelo** [comment]
Hi! As far as I can tell, my domain name provider does not let me add a certificate, unless I pay them for it, which, given the open-source nature of the project and the fact that no sensitive information is ever transferred over the website, I opted not to do. 

However, if there is a way to actually use Github Pages' SSL certificate, I would be more than willing to configure the website to use it, as it will also be beneficial to SEO. I have absolutely no clue how to do this and I haven't managed to find any sources online. If you have any ideas on what I could do or know any useful sources, feel free to inform me!

**Comment by snewell92** [comment]
Oh my, interesting that you domain name provider doesn't let you use lets encrypt certificates... rough!

Actually.. at first I didn't think [custom domains with GitHubPages](https://help.github.com/articles/quick-start-setting-up-a-custom-domain/) worked... but [maybe it does](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)?

Actually after more reading it appears that there are [plenty of examples](https://github.com/showcases/github-pages-examples) that use [custom](https://jekyllrb.com/) [domains](http://goratchet.com/). The jekyll docs in particular use a custom domain name and use GitHub's ssl cert - which is exactly what you asked.

That being said, I still don't know if your provider's restrictions would still apply even though you'd be passing requests from that domain to github, although I wouldn't think so... Worth a shot in a test repo possibly... if you have a spare domain with the same provider you can test with.

Since the documentation is just a static site, another option is to just take the current documentation site and embed it into this repo, or make a new public repo for it that uses the default naming scheme - but doing this would give up the nice, terse domain name _minicss.org_ - which I suppose is less than ideal.

**Comment by Chalarangelo** [comment]
I contacted support and they said I cannot actually use the SSL from Github Pages, but I could move my hosting to their hosting provider (not for free) and then use a free SSL certificate. Thus, I won't be moving the project's documentation to HTTPS anytime soon. At least, the distributables are all secure behind HTTPS, thanks to the amazing people behind the CDNs we're using, so no worries there!

**Comment by snewell92** [comment]
Thanks for looking into it!
