### ISSUE TITLE
Form field validation examples?

### ISSUE THREAD

**Issue by kokujin** [Chalarangelo/mini.css#92]
Could someone point me to the form field validation examples? Thanks

**Comment by Chalarangelo** [comment]
Hello, there! What exactly do you mean by form field validation examples?

**Comment by kokujin** [comment]
HI @Chalarangelo , I meant that I did not see any examples of how fields are marked as invalid and error messages are displayed.

**Comment by Chalarangelo** [comment]
Well, invalid fields are marked as invalid the normal way (i.e. if you type something like `blahblah` in a `email` field, it will go red). I did not include invalid or hover-over fields in the documentation page, as this can be easily tested right there, but I might update the docs soon enough (although there's a few changes I am going to be making in the next few days to the input_control module, so it might be a while before these are shown).

As far as error messages are concerned, there is no built-in support, however you can use some other module or just plaintext to show error messages as necessary. I will look into the idea, if it can be implemented with a pure CSS solution (I have something in mind), although this will certainly take a long time to build and test, as there are a lot of things that need to be considered.
