### ISSUE TITLE
Header background-color not included if equal to to back-color

### ISSUE THREAD

**Issue by phuhl** [Chalarangelo/mini.css#94]
This is only a problem if the header is sticky, but then a background color is necessary or otherwise the stuff behind the header can shine through. To fix this i recommend changing these lines (40-42 _navigation.scss)

    @if $header-back-color != $back-color {
       background: $header-back-color;
    }

to

  
    background: $header-back-color;

**Comment by Chalarangelo** [comment]
Good catch! I can see how this could be a potential problem. Will fix today, releasing a hotfix, along with some very minor documentation updates that have been pushed back for a couple of weeks now, due to me being on vacation. Thank you very much for your contribution! 👍
