### ISSUE TITLE
Table not correctly displayed on mobile

### ISSUE THREAD

**Issue by akak0r** [Chalarangelo/mini.css#95]
Hi,

I created a website using minicss: [ISIN Database](https://www.isindb.com). The search results in a table look fine on a desktop, but not on mobile (try for example searching for 'Shell').
Can you tell me how to fix this? Thanks!!

**Comment by Chalarangelo** [comment]
Hi,

I can suggest two options:

1. Use `&nbsp;` instead of normal spaces, this will make the cards display as intended. (Recommended)
2. Apply `.preset` to the `<table>` element, making it non-responsive, using the desktop layout instead.
