### ISSUE TITLE
Text area in Sucroa flavor goes beyond the Comments' dimensions

### ISSUE THREAD

**Issue by quantuumsnot** [Chalarangelo/mini.css#98]
Is this the expected behaviour of Comments' textarea?

https://github.com/quantuumsnot/bugs-found-collection/blob/master/minicss%20problem.png
Screenshot from Codepen

Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit), Windows 7 SP1 64bit

**Comment by Chalarangelo** [comment]
In general, yes. However, this looks bad, so I took a minute to update the template to size properly. I will investigate this situation further, in case this is a problem that should be dealt with. Thanks for reporting it!
